## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Airvore"
theme = "hugo-story"
copyright = "All rights reserved CalCool Studios and authors ©{year}"
titleCaseStyle = "Chicago"
timeZone = "Europe/Paris"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

## Directories
#archetypeDir = "archetypes"
#assetDir = "assets"
#resourceDir = "resources"
#publishDir = "public"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

enableGitInfo = "true"
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "G-RP8E0TN2P6"  # only in production

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

## Language parameters
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = "true"
disableLanguages = ['pl','it','es']

[languages]
# If a [key] is defined, all the subkeys must be defined or they will be treated as absent for that language.
# It is a mechanism that allows tailoring the interface to each language also by removing UI elements.
  [languages.fr]
    languageName = "Français"
    weight = 2
    [languages.fr.params]
      [languages.fr.params.social]
	github = "https://github.com/CriticalOptimisation/airvore"
	twitter = "https://twitter.com/jpeuvedic"
	email = "airvore@calcool.ai"
	instagram = "https://instagram.com"
	linkedin = "https://www.linkedin.com/in/jean-marc-le-peuvedic/?locale=fr_FR"
      [languages.fr.params.aria]
	github = "Voir le code source de ce site sur GitHub"
	twitter = "Regardez nos Tweets sur Twitter"
	email = "Envoyez-nous un mail"
	instagram = "Visiter notre Instagram"
	linkedin = "Le profil LinkedIn de l'auteur"
	telegram = "Rejoignez notre groupe Telegram"
	
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.params]
      [languages.en.params.aria]
	github = "Read the source code of this website on GitHub"
	twitter = "Read our Tweets on Twitter"
	email = "Send us an email"
	instagram = "Visit our Instagram"
	linkedin = "The author's LinkedIn profile"
	telegram = "Join our Telegram group"

[params]
  favicon = true
  AuthorName = "Laurent Castaignède"

[params.social]
  github = "https://github.com/CriticalOptimisation/airvore"
  twitter = "https://twitter.com/jpeuvedic"
  email = "airvore@calcool.ai"
  instagram = "https://instagram.com"
  linkedin = "https://www.linkedin.com/in/jean-marc-le-peuvedic/"
#  telegram = "https://telegram.org"

[params.aria]
# Default accessible link text
  github = "Voir le code source de ce site sur GitHub"
  twitter = "Regardez nos Tweets sur Twitter"
  email = "Envoyez-nous un mail"
  instagram = "Visiter notre Instagram"
  linkedin = "Le profil LinkedIn de l'auteur"
  telegram = "Rejoignez notre groupe Telegram"

[params.asset]
  fontawesome_js = ["https://kit.fontawesome.com/74fa1d8c3d.js"]


## -----------------------------------------------
## Configure sitemap.xml
## -----------------------------------------------
## Default changefreq and priority should be overridden in front matter file (in content).
[sitemap]
  filename = 'sitemap.xml'
  changefreq = 'daily'
  priority = 0.5

## -----------------------------------------------
## Image processing pipe
## -----------------------------------------------
[imaging]
## Default values are commented out.
  anchor = 'Smart'
#  bgColor = '#ffffff'
  hint = 'photo'
#  quality = 75
  resampleFilter = 'Box'
  [imaging.exif]
    disableDate = false
    disableLatLong = true
#    excludeFields = ''
#    includeFields = ''  

## -----------------------------------------------
## Search Engine Optimisation
## -----------------------------------------------

