## -----------------------------------------------
## Basic Configuration (development)
## -----------------------------------------------

title = "Hugo Story"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

## Built-in server configuration
watch = "true"

[server]
[[server.headers]]
  for = '/*'
  [server.headers.values]
    Content-Security-Policy = "default-src 'self';style-src 'self' https://fonts.googleapis.com  'sha256-t5UevlZFg4AscJaQBUf/8TJdDo/qHa8JaDSW3ITQjJs=' 'sha256-4Cqrb9+UVnxYYbmkWOWFDIDtOh5RSNjO41psqDRsOhw=' 'sha256-PlTkgCr7abMkWLmLhbsMIx5IZAK+f/mrWppZJA1W79M='; font-src 'self' https://fonts.gstatic.com https://*.fontawesome.com;img-src data: 'self';script-src 'self' https://www.googletagmanager.com/ https://www.google-analytics.com/ https://kit.fontawesome.com/ 'sha256-69UL0gXNsUfacQNO+lVXToGgfheKCIInl4fwPTPkgak=' 'sha256-/F7HKoI0UG7E/LXno/mf5iaMdCElzxnYmm7+y2K6Oqc='; connect-src ws://localhost:1313/livereload https://*.google-analytics.com https://*.fontawesome.com;frame-ancestors 'none';"
    X-Frame-Options = 'DENY'
    Permissions-Policy = "accelerometer=(), camera=(), display-capture=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), fullscreen=(), screen-wake-lock=()"
  
[[server.headers]]
  for = '/'
  [server.headers.values]
    Access-Control-Allow-Origin = "*"
    
[[server.headers]]
  for = '/**/*'
  [server.headers.values]
    Access-Control-Allow-Origin = "http://localhost:1313"
  

## -----------------------------------------------
## Hugo Built-in Features (see hugo.toml)
## -----------------------------------------------

enableGitInfo = "true"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Development configuration"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]

[Params.asset]

