## -----------------------------------------------
## Basic Configuration (development)
## -----------------------------------------------

title = "Hugo Story"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

## Built-in server configuration
watch = "true"

[server]
[[server.headers]]
  for = '/*'
  [server.headers.values]
    Content-Security-Policy = "default-src 'self';style-src 'self' https://fonts.googleapis.com 'sha256-t5UevlZFg4AscJaQBUf/8TJdDo/qHa8JaDSW3ITQjJs=' 'sha256-jltyiCS6pvytLMCNlcJTdKgVaSVp6+pZoGQyUv5F2io='; font-src 'self' https://fonts.gstatic.com;img-src data: 'self';script-src 'self' https://www.googletagmanager.com/ https://www.google-analytics.com/ 'sha256-69UL0gXNsUfacQNO+lVXToGgfheKCIInl4fwPTPkgak=' 'sha256-/F7HKoI0UG7E/LXno/mf5iaMdCElzxnYmm7+y2K6Oqc='; connect-src https://*.google-analytics.com;frame-ancestors 'none';"
    X-Frame-Options = 'DENY'
    Permissions-Policy = "accelerometer=(), camera=(), display-capture=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), fullscreen=(), screen-wake-lock=()"
  
[[server.headers]]
  for = '/'
  [server.headers.values]
    Access-Control-Allow-Origin = "*"
    
[[server.headers]]
  for = '/**/*'
  [server.headers.values]
    Access-Control-Allow-Origin = "http://localhost:1313"
  

## -----------------------------------------------
## Hugo Built-in Features (see hugo.toml)
## -----------------------------------------------

enableGitInfo = "true"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/caressofsteel/"
  twitter = "https://twitter.com/caressofsteel_"
  email = "caressofsteel@protonmail.com"
  instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"
  telegram = "https://telegram.org"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]
