## -----------------------------------------------
## Basic Configuration (production)
## -----------------------------------------------

title = "Hugo Story"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "https://airvore.fr"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

enableGitInfo = "false"
enableRobots = "true"
googleAnalytics = "G-RP8E0TN2P6"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
#  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
#  logo = "images/banner.jpg"
#  favicon = true

[Params.social]
  github = "https://github.com/CriticalOptimisation/"
  twitter = "https://twitter.com/jpeuvedic"
  email = "laurentcastaignede@orange.fr"
  instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"
#  telegram = "https://telegram.org"

