## -----------------------------------------------
## Basic Configuration (production)
## -----------------------------------------------

title = "Hugo Story"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "https://airvore.fr"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

enableGitInfo = "false"
enableRobots = "true"
googleAnalytics = "G-RP8E0TN2P6"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]

[Params.social]

